version: 2

models:
  - name: inventory_levels
    description: >
      Core table containing inventory data including total inventory value over time, inventory turnover ratio, and inventory aging analysis.
    columns:
      - name: month
        description: The month for which the inventory metrics are calculated.
        tests: []
        meta: {}
        type: TIMESTAMP
      - name: total_inventory_value
        description: The total value of inventory for the corresponding month.
        tests: []
        meta: {}
        type: FLOAT64
      - name: inventory_turnover_ratio
        description: The ratio of inventory turnover calculated over the specified period.
        tests: []
        meta: {}
        type: FLOAT64
      - name: age_range
        description: The age range of inventory items categorized based on their age.
        tests: []
        meta: {}
        type: STRING
      - name: inventory_value
        description: The value of inventory items falling within the specified age range.
        tests: []
        meta: {}
        type: FLOAT64

  - name: customer_retention_rate
    description: >
      Model calculating customer retention rate over time.
    columns:
      - name: year
        description: The year of the data.
        tests: []
        meta: {}
        type: INT64
      - name: month_name
        description: The name of the month.
        tests: []
        meta: {}
        type: STRING
      - name: distinct_customers
        description: The number of distinct customers in the given month.
        tests: []
        meta: {}
        type: INT64
      - name: rolling_customers
        description: The cumulative number of distinct customers up to the given month.
        tests: []
        meta: {}
        type: INT64
      - name: customer_retention_rate
        description: The retention rate of customers for the given month.
        tests: []
        meta: {}
        type: FLOAT64

  - name: financial_commitments
    description: >
      Model analyzing financial commitments fulfillment rate.
    columns:
      - name: department_name
        description: The name of the department.
        tests: []
        meta: {}
        type: STRING
      - name: market
        description: The market category.
        tests: []
        meta: {}
        type: STRING
      - name: category_name
        description: The name of the product category.
        tests: []
        meta: {}
        type: STRING
      - name: total_committed_funds
        description: The total committed funds for the department, market, and category.
        tests: []
        meta: {}
        type: FLOAT64
      - name: commitment_fulfillment_rate
        description: The rate of commitment fulfillment.
        tests: []
        meta: {}
        type: FLOAT64

  - name: fraud_detection_model
    description: >
      Model for detecting potential fraudulent activities.
    columns:
      - name: order_customer_id
        description: The ID of the customer associated with the order.
        tests: []
        meta: {}
        type: STRING
      - name: avg_order_total
        description: The average order total for the customer.
        tests: []
        meta: {}
        type: FLOAT64
      - name: num_orders
        description: The number of orders placed by the customer.
        tests: []
        meta: {}
        type: INT64

  - name: overall_performance
    description: >
      Model presenting overall sales performance and operational efficiency metrics.
    columns:
      - name: year
        description: The year of the data.
        tests: []
        meta: {}
        type: INT64
      - name: month_name
        description: The name of the month.
        tests: []
        meta: {}
        type: STRING
      - name: total_sales
        description: The total sales for the month.
        tests: []
        meta: {}
        type: FLOAT64
      - name: avg_profit_margin
        description: The average profit margin for the month.
        tests: []
        meta: {}
        type: FLOAT64
      - name: avg_actual_shipment_days
        description: The average actual shipment days for the month.
        tests: []
        meta: {}
        type: FLOAT64
      - name: avg_scheduled_shipment_days
        description: The average scheduled shipment days for the month.
        tests: []
        meta: {}
        type: FLOAT64

  - name: payment_delays
    description: >
      Model analyzing payment delays.
    columns:
      - name: delivery_status
        description: The status of delivery.
        tests: []
        meta: {}
        type: STRING
      - name: avg_payment_delay
        description: The average payment delay.
        tests: []
        meta: {}
        type: FLOAT64
      - name: count_of_orders
        description: The count of orders.
        tests: []
        meta: {}
        type: INT64
