version: "3.6"

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
networks:
  default:
    name: ${PROJECT_NAME}-network
    external: true

services:
  
  jupyterlab:
    image: jupyterlab
    container_name: ${PROJECT_NAME}-jupyterlab
    volumes:
      - shared-workspace:/opt/workspace
    env_file:
      - .env
    ports:
      - 8888:8888

  spark-master:
    image: spark-master
    container_name: ${PROJECT_NAME}-spark-master
    volumes:
      - shared-workspace:/opt/workspace
    environment:
      SPARK_LOCAL_IP: spark-master
    env_file:
      - .env
    ports:
      - 8080:8080
      - 7077:7077
    
  spark-worker-1:
    image: spark-worker
    container_name: ${PROJECT_NAME}-spark-worker-1
    depends_on:
      - spark-master
    volumes:
      - shared-workspace:/opt/workspace
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=4g
    env_file:
      - .env
    ports:
      - 8083:8081

    
