version: 2

sources:
  - name: staging
    database: gothic-sylph-387906
    schema: supply_chain_data

    tables:
      - name: dim_customer
        description: Dimension table for customer data
        columns:
          - name: Customer_Id
            description: Unique identifier for customers
            tests: {}
            meta: {}
            type: STRING
          - name: Customer_Email
            description: Email address of the customer
            tests: {}
            meta: {}
            type: STRING
          - name: Customer_Fname
            description: First name of the customer
            tests: {}
            meta: {}
            type: STRING
          - name: Customer_Lname
            description: Last name of the customer
            tests: {}
            meta: {}
            type: STRING
          - name: Customer_Segment
            description: Segment of the customer
            tests: {}
            meta: {}
            type: STRING
          - name: Customer_City
            description: City of the customer
            tests: {}
            meta: {}
            type: STRING
          - name: Customer_Country
            description: Country of the customer
            tests: {}
            meta: {}
            type: STRING
          - name: Customer_State
            description: State of the customer
            tests: {}
            meta: {}
            type: STRING
          - name: Customer_Street
            description: Street address of the customer
            tests: {}
            meta: {}
            type: STRING
          - name: Customer_Zipcode
            description: ZIP code of the customer
            tests: {}
            meta: {}
            type: STRING

      - name: dim_product
        description: Dimension table for product data
        columns:
          - name: Product_Card_Id
            description: Unique identifier for products
            tests: {}
            meta: {}
            type: STRING
          - name: Product_Category_Id
            description: Identifier for the category of the product
            tests: {}
            meta: {}
            type: STRING
          - name: Category_Name
            description: Name of the category
            tests: {}
            meta: {}
            type: STRING
          - name: Product_Description
            description: Description of the product
            tests: {}
            meta: {}
            type: STRING
          - name: Product_Image
            description: URL of the product image
            tests: {}
            meta: {}
            type: STRING
          - name: Product_Name
            description: Name of the product
            tests: {}
            meta: {}
            type: STRING
          - name: Product_Price
            description: Price of the product
            tests: {}
            meta: {}
            type: STRING
          - name: Product_Status
            description: Status of the product
            tests: {}
            meta: {}
            type: STRING

      - name: dim_location
        description: Dimension table for location data
        columns:
          - name: Order_Zipcode
            description: ZIP code of the order location
            tests: {}
            meta: {}
            type: STRING
          - name: Order_City
            description: City of the order location
            tests: {}
            meta: {}
            type: STRING
          - name: Order_State
            description: State of the order location
            tests: {}
            meta: {}
            type: STRING
          - name: Order_Region
            description: Region of the order location
            tests: {}
            meta: {}
            type: STRING
          - name: Order_Country
            description: Country of the order location
            tests: {}
            meta: {}
            type: STRING
          - name: Latitude
            description: Latitude of the order location
            tests: {}
            meta: {}
            type: STRING
          - name: Longitude
            description: Longitude of the order location
            tests: {}
            meta: {}
            type: STRING

      - name: dim_order
        description: Dimension table for order data
        columns:
          - name: Order_Id
            description: Unique identifier for orders
            tests: {}
            meta: {}
            type: STRING
          - name: Order_date
            description: Date of the order
            tests: {}
            meta: {}
            type: STRING
          - name: Order_Customer_Id
            description: Identifier for the customer who placed the order
            tests: {}
            meta: {}
            type: STRING
          - name: Order_Item_Id
            description: Identifier for the ordered item
            tests: {}
            meta: {}
            type: STRING
          - name: Order_Item_Discount
            description: Discount applied to the ordered item
            tests: {}
            meta: {}
            type: STRING
          - name: Order_Item_Discount_Rate
            description: Rate of discount applied to the ordered item
            tests: {}
            meta: {}
            type: STRING
          - name: Order_Item_Product_Price
            description: Price of the ordered item
            tests: {}
            meta: {}
            type: STRING
          - name: Order_Item_Profit_Ratio
            description: Profit ratio of the ordered item
            tests: {}
            meta: {}
            type: STRING
          - name: Order_Item_Quantity
            description: Quantity of the ordered item
            tests: {}
            meta: {}
            type: STRING
          - name: Sales_per_customer
            description: Sales per customer
            tests: {}
            meta: {}
            type: STRING
