version: '3'
networks:
  default:
    name: ${PROJECT_NAME}-network
    external: true
services:
  mageai:
    image: mageai/mageai:latest
    container_name: ${PROJECT_NAME}-mageai
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - ${MAGE_PORT}:6789
    volumes:
      - .:/home/src/
      
    restart: on-failure:5


