blocks:
- all_upstream_blocks_executed: true
  color: blue
  configuration: {}
  downstream_blocks: []
  executor_config: null
  executor_type: local_python
  has_callback: false
  language: python
  name: spark_session
  retry_config: null
  status: failed
  timeout: null
  type: custom
  upstream_blocks: []
  uuid: spark_session
cache_block_output_in_memory: false
callbacks: []
concurrency_config: {}
conditionals: []
created_at: '2024-03-14 05:56:52.953099+00:00'
data_integration: null
description: null
executor_config: {}
executor_count: 1
executor_type: null
extensions: {}
name: broken dawn
notification_config: {}
remote_variables_dir: null
retry_config: {}
run_pipeline_in_one_process: false
settings:
  triggers: null
spark_config: {}
tags: []
type: python
uuid: broken_dawn
variables_dir: /home/src/mage_data/ashraf-magic
widgets: []
